Create Basic Carousel Component & Integrate on Main Page
joe-studer-18/mst-ka-site pull request #139
Opened 2022-05-16 01:07 UTC by joe-studer-18

Creating a basic carousel component w/ MUI

Note theres a lot of todos here, since we can't link to pages that we haven't made yet.

2022-05-16 02:26 UTC, joe-studer-18 commented
Changes are live here: https://react-mst-ka.firebaseapp.com/

2022-05-16 02:48 UTC, jaredwhanisch requested changes
The carousel looks awesome! Just a few comments on keeping everything consistent throughout the website as a whole with using MUI. If you have any questions just let me know!

Also, are the images in the _/public/index_ directory duplicates of the images in _/public/**images**/index_?

2022-05-16 02:48 UTC, jaredwhanisch commented on components/ImgCarousel/ImgCarousel.js
> +          <a href={props.image.button_link}>
You conveniently do not need to wrap buttons in an `<a>` tag to link them, an MUI `<Button/>` component has a built in href prop that you can link directly. I believe it would look a little something like this: 

```javascript
<Button href={props.image.button_link} variant="contained">
    {props.image.button_text}<ArrowRightIcon />
</Button>
```

For more info see MUI's [Button API](https://mui.com/material-ui/api/button/)

2022-05-16 02:48 UTC, jaredwhanisch commented on components/ImgCarousel/ImgCarousel.js
> +          <a href="/ApplyOnline.html">
Same comment as above. Use href prop instead of wrapping button in an `<a>` tag

2022-05-16 02:48 UTC, jaredwhanisch commented on components/ImgCarousel/ImgCarousel.js
> +      <div style={{position: "relative", width: "100%", height: "600px"}}>
Same comment as with the `<ButtonDiv />`. It may be better to make this div a `<Container />` component instead.

2022-05-16 02:48 UTC, jaredwhanisch commented on components/ImgCarousel/ImgCarousel.js
> +  const ImageHeader = styled("h1")(() => ({
I think these styled components for the headings could be replaced with the [`<Typography />` MUI component](https://mui.com/material-ui/react-typography/). This will allow you to style them individually with the `sx` prop as well as designate what html element you would like them to be with the `variant` prop.

2022-05-16 02:48 UTC, jaredwhanisch commented on components/ImgCarousel/ImgCarousel.js
> +  const ButtonDiv = styled("div")(() => ({
To keep the styling consistent, I would recommend using the [<Container /> MUI component](https://mui.com/material-ui/api/container/) instead of a styled div. You can put the styles in the `sx` prop and even specify the <Container /> as a div using the `component` prop.

2022-05-16 02:48 UTC, jaredwhanisch commented on components/ImgCarousel/ImgCarousel.js
> +      imgs.map( (img, i) => <_CreateImage key={i} image={img} /> )
Good use of map and I'm glad you figured out that you have to give each `<_CreateImage />` component a unique key. I got stuck forever on that when working with the navbar buttons.

2022-05-16 02:48 UTC, jaredwhanisch commented on package.json
> +    "next-image-export-optimizer": "^0.9.6",
Thanks for thinking of adding this! It's good thinking to get this out of the way before we start adding a ton of images to the site!

2022-06-20 15:25 UTC, jaredwhanisch commented
Just noticed this, it seems there is a bug with the react-material-ui-carousel package where if you start clicking the arrow buttons too quickly, the carousel will collapse to zero height. Luckily, a [fix was added](https://github.com/Learus/react-material-ui-carousel/blob/master/CHANGELOG.md#fixed) at the end of May, and you should just have to update the package to v3.4.2.

2022-07-16 19:49 UTC, joe-studer-18 commented on components/Layout/Layout.js
> +      <Safe.script type="application/ld+json">{
It's just there to wrap this block as a script while being react compliant. The script just exists to be parsed by search engine webcrawlers to make our results a bit better.

2022-11-16 05:12 UTC, jaredwhanisch commented
No longer relevant due to #154

2022-11-16 05:12 UTC, closed without merging