Nklein/newphotos
joe-studer-18/mst-ka-site pull request #80
Opened 2021-03-01 21:09 UTC by noahklein00

2021-03-02 03:15 UTC, joe-studer-18 requested changes
Correct me if I'm wrong, but are the images in the "website pics" used anywhere?

If yes, let's rename the images to be a bit more descriptive & move them directly in to the img/ subdir. 

If no, can you remove that subdir?

2021-03-08 23:09 UTC, joe-studer-18 approved these changes

2021-03-11 02:57 UTC, jaredwhanisch commented
Were we going to update the rest of the photos that are outdated? Or is that something that will happen in the future?

2021-03-13 17:14 UTC, joe-studer-18 commented
We can leave that to a future PR - the officer page needs to be updated soon, since the website is going live this weekend.

2021-03-13 19:41 UTC, merged